import mysql.connector as sql
conn=sql.connect(host='localhost',user='root',passwd='computer',database='UPSC')
#if conn.is_connected():
      #print('connected sucessfully')
c1=conn.cursor()
c1.execute("select * from login_info")
dat=c1.fetchall()

user=input("Enter user name")
passwd=input("Enter the password")
if (user,passwd) in dat:
      print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ UPSC REGISTARATION$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
      print("1:ADD DETAILS")
      print("2:VIEW DETAILS")
      print("3:QUIT")
      ch=int(input("Enter the choice--"))
      if ch==1:
            c1.execute("select * from registration_information")
            v_data=c1.fetchall()
            v_count=len(v_data)
            
            v_reg_no=(v_count+1)
            v_ea=input("Enter the examination applied--")
            v_yr=input("Enter the year--")
            v_name=input("Enter your name--")
            v_gen=input("Enter your gender--")
            v_dob=input("Enter your date of birth--")
            v_f_na=input("Enter you father name--")
            v_m_na=input("Enter your mother name--")
            v_nat=input("Enter your nationality--")
            v_mar_st=input("Enter your marital staus--")
            v_comm=input("Enter your community--")
            v_min=input("Do you belong to minority--")
            v_add1=input("Enter address line1--")
            v_add2=input("Enter address line2--")
            v_add3=input("Enter address line3--")
            v_dist=input("Enter your district--")
            v_state=input("Enter your state--")
            v_pin=input("Enter your pin code--")
            v_pho=input("Enter your phone number--")
            v_mob=input("Enter your mobile number--")
            v_ema=input("Enter your mail ID--")
            v_edu=input("Enter your education qualification--")
            v_aadh=input("Enter your aadhar number--")
            v_pre=input("Enter your preferance--")
            v_p_f=input("Did you ever fail in CPSS(Computerised Pilot Selection System) or""\n"" PABT (Pilot Aptitude Battery Test) Examination of Air Force--")
            v_stu_sa=input("Whether Student of Sainik/Military School--")
            v_son_mil=input("Whether Son of JCO/NCO/Other Rank officers and studying in Sainik Military School--")
            v_sql=("insert into  registration_information values ("+v_aadh+","+"'"+v_f_na+"'"+","+"'"+v_m_na+"','"+v_ea+"',"+v_yr+",'"+v_gen+"','"+v_dob+"','"+v_nat+"','"+v_mar_st+"','"+v_comm+"','"+v_min+"','"+v_add1+"','"+v_add2+"','"+v_add3+"','"+v_dist+"','"+v_state+"',"+v_pin+","+v_pho+","+v_mob+",'"+v_ema+"','"+v_edu+"','"+v_pre+"','"+v_p_f+"','"+v_stu_sa+"','"+v_son_mil+"','"+v_name+"',"+str(v_reg_no)+")")
            print(v_sql)
            print("registered successfully your registartion number is--",v_reg_no)
            c1.execute(v_sql)
            conn.commit()
      elif ch==2:
            reg=int(input("Enter the registartion number"))
            v_ch=("select * from registration_information where reg_no="+str(reg)) 
            c1.execute(v_ch)
            data=c1.fetchone()
            print('\n')
            print("Registration no--",data[26])
            print ("Examination applied--",data[3])
            print ("Year  --",data[4])
            print("Name    --",data[25])
            print ("Gender  --",data[5])
            print ("Date of birth --",data[6])
            print("Father name --",data[1])
            print("Mother name --",data[2])
            print("Nationality  --",data[7])
            print("Marital status--",data[8])
            print("Community--",data[9])
            print("Minority  --",data[10])
            print("Address line1 --",data[11])
            print("Address line2 --",data[12])
            print("Address line3 --",data[13])
            print("District --",data[14])
            print("State --",data[15])
            print("Pin code    --",data[16])
            print("Phone no    --",data[17])
            print("Mobile no--",data[18])
            print("E mail --",data[19])
            print("Education_qualification--",data[20])
            print("Aadhar no  --",data[0])
            print("Preferance --",data[21])
            print("Cds\pabt passed --",data[22])
            print("Belong to sainik\miltary school--",data[23])
            print("Son of miltary man adnd studying in saink miltary school--",data[24])
            
            
      elif ch==3:
            print("QUITTING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

      else :
            print("INVALID CHOICE PLEASE TRY AGAIN")
